defaults:
    # options: 
    #   search_nasbench201: search phase settings for nasbench 201
    #   search_pcdarts:search phase settings for pcdarts on CIFAR-10
    #   eval: evaluation phase settings for darts search space on CIFAR-10
    - mode: ???
    # options:
    #   edarts: GAEA DARTS
    #   eedarts: GAEA DARTS with edge learning
    #   egdas: GAEA GDAS
    - nas_algo: ???
      optional: true # not actually optional but flag needed for parsing
    # options:
    #   [fill in with file from search_method/[nas_algo] folder]
    #   e.g. method_edarts_space_nasbench201
    - search_config: ???
      optional: true # not actually optional but flag needed for parsing
    - search_method: ${defaults.1.nas_algo}/${defaults.2.search_config}

run:
    s3_bucket: null
    seed: ???
    data: /data
    dataset: cifar10 
    epochs: ???
    scheduler_epochs: 50
    n_threads_data: 0
    autodl: /code/AutoDL
    report_freq: 50
    test_code: false
    gpu: 0

search:
    # Bi-level or single-level optimization
    single_level: ???
    # Whether to exclude zero op from search space
    exclude_zero: ???
    track_running_stats: true 


hydra:
    run:
        dir: /data/eval-space-darts-${train.arch}-${run.dataset}-${run.seed}


